# Generated by Django 3.0.6 on 2020-05-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0003_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
