# Generated by Django 3.0.6 on 2020-05-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0005_auto_20200526_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], default=None, max_length=20),
        ),
    ]
