# Generated by Django 3.0.6 on 2020-05-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0009_auto_20200526_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='info',
            name='type_of_user',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Clothing', 'Clothing'), ('other', 'other'), ('Footwear', 'Footwear'), ('Electronics', 'Electronics'), ('Books', 'Books')], default='other', max_length=20),
        ),
    ]
