# Generated by Django 3.0.6 on 2020-05-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0011_auto_20200527_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Delivery_address',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='info',
            name='type_of_user',
            field=models.CharField(choices=[('Seller', 'Seller'), ('Buyer', 'Buyer')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Footwear', 'Footwear'), ('Electronics', 'Electronics'), ('Books', 'Books'), ('Clothing', 'Clothing'), ('other', 'other')], default='other', max_length=20),
        ),
    ]
