# Generated by Django 3.0.6 on 2020-05-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0013_auto_20200527_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='type_of_user',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery'), ('Pending', 'Pending')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('other', 'other'), ('Clothing', 'Clothing'), ('Electronics', 'Electronics'), ('Footwear', 'Footwear'), ('Books', 'Books')], default='other', max_length=20),
        ),
    ]
