# Generated by Django 3.0.6 on 2020-05-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0017_auto_20200527_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Books', 'Books'), ('other', 'other'), ('Footwear', 'Footwear'), ('Clothing', 'Clothing')], default='other', max_length=20),
        ),
    ]
