# Generated by Django 3.0.6 on 2020-05-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0018_auto_20200527_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Out for delivery', 'Out for delivery')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Footwear', 'Footwear'), ('Electronics', 'Electronics'), ('Books', 'Books'), ('Clothing', 'Clothing'), ('other', 'other')], default='other', max_length=20),
        ),
    ]
