# Generated by Django 3.0.6 on 2020-05-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0020_auto_20200527_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='product_image1',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image2',
            field=models.ImageField(default='default.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image3',
            field=models.ImageField(default='default.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image4',
            field=models.ImageField(default='default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='info',
            name='type_of_user',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Clothing', 'Clothing'), ('other', 'other'), ('Electronics', 'Electronics'), ('Footwear', 'Footwear'), ('Books', 'Books')], default='other', max_length=20),
        ),
    ]
